services:
  - type: web
    name: quickbite-backend
    runtime: docker
    region: virginia
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-d9ggdfupbkes73cnbptg-a.virginia-postgres.render.com/quickbite_y2l4
      - key: DB_USERNAME
        value: quickbite_user
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
